app = "carrier-sales-db"
primary_region = "bos"

[build]
  image = "mysql:8"

[env]
  MYSQL_DATABASE = "carrier_db"
  MYSQL_USER     = "carrier_user"
  MYSQL_PASSWORD = "supersecret"
  MYSQL_ROOT_PASSWORD = "rootsecret"

[[mounts]]
  source      = "mysqldata"
  destination = "/var/lib/mysql"

[experimental]
  auto_rollback = false
  auto_start_machines = true
  auto_stop_machines  = false